### ISSUE TITLE
tempspec containers of handles

### ISSUE THREAD

**Issue by cguebert** [Sami-Vuorela/aatc#4]
(I am working with the refactor branch)
I have encountered a problem trying to work with a vector of handles, registered in my application.
What I did was registering a `tempspec::vector<MyClass*>` with the script type being `MyClass@`.
My issue is that the reference counter of the handles is not managed by the vector class, and the objects are destroyed while their handles are in the container.

Should I be using another class or am I missing something?

PS: for the compilation in VS2013, I add to modify aatc_templatemagic.hpp:
Replace instances of `template<int> typename` with `template<int> class`

**Comment by Sami-Vuorela** [comment]
You should use an aatc::container::templated::vector instead for all your handle containing needs.  
Tempspec'd containers do not currently support angelscript handles because templated versions of containers already handle handles with very little overhead compared to tempspec'd containers.  
I should probably update the documentation page of tempspecs with more info about their quirks.  
Why did you decide to register a tempspec of MyCppClass\* anyway? Were you just looking for performance? Was the aatc::container::templated::vector cpp side interface too annoying because its all voidpointers?  
I suppose it could be possible to make AATC tempspec'd containers handle handles, but users would have to specialize yet another functor template to tell AATC how to increment and decrement the handle.

**Comment by cguebert** [comment]
I just didn't think of it, I believed tempspec'd containers were the only ones that could be used on the application side. (I just began using AngelScript, so don't know all the details)

I also was blocked because I created a class templated by a vector like this: `Field<vector<MyClass@>@>`. For this to work, I had to register the templated vector first.
If I just rename this class without the templates, I can use aatc::container::templated::vector instead.

Thank you for your answer, and your library!
